CREATE TABLE Usuario(
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
nome TEXT NOT NULL,
senha TEXT NOT NULL
);

CREATE TABLE Copia(
CodigoDeBarra INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
DataDeImpressao TEXT NOT NULL
);

CREATE TABLE Obra(
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
titulo TEXT NOT NULL,
autor TEXT NOT NULL,
genero TEXT NOT NULL,
tipo TEXT NOT NULL,
Copia_CodigoDeBarra INTEGER NOT NULL,
FOREIGN KEY(Copia_CodigoDeBarra) REFERENCES Copia(CodigoDeBarra)
);

CREATE TABLE Emprestimo(
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
usuario_id INTEGER NOT NULL,
DataDeDevolucao TEXT NOT NULL,
FOREIGN KEY (usuario_id) REFERENCES Usuario(id)
 );
